### ISSUE TITLE
Add flatpak

### ISSUE THREAD

**Issue by TinF0ilHat1** [Turtlecute33/Clean-linux-script#2]
You might add some lines for flatpak, starting from: 
`flatpak uninstall --unused`

Something like this would work [?]
`if command -v flatpak> /dev/null 2>&1; then 
  flatpak uninstall --unused -y
fi`

**Comment by Turtlecute33** [comment]
> You might add some lines for flatpak, starting from: `flatpak uninstall --unused`
> 
> Something like this would work [?] `if command -v flatpak> /dev/null 2>&1; then flatpak uninstall --unused -y fi`

That's a great idea! I could update the script to check if Flatpak is installed and then run the following commands:

flatpak update
flatpak uninstall --unused

Would you like to create a pull request, or was this just a suggestion?

**Comment by TinF0ilHat1** [comment]
> Would you like to create a pull request, or was this just a suggestion?

Just a feedback

**Comment by st3b1t** [comment]
the same for the fucked **snap**:
```bash
snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
```
